# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_squashed_0002_auto_20160625_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='ファイル名')),
                ('data', models.FileField(upload_to='student_works', verbose_name='データ')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': '生徒の作品',
                'verbose_name': '生徒の作品',
            },
        ),
    ]
