# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usrname',
            field=models.CharField(default=datetime.datetime(2016, 6, 18, 14, 33, 44, 720387, tzinfo=utc), max_length=100, verbose_name='お名前'),
            preserve_default=False,
        ),
    ]
