# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_comment_usrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='usrname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
