# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20160624_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='usrename',
            field=models.CharField(default='anonymous', max_length=200, verbose_name='名前'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=500, verbose_name='メッセージ'),
        ),
    ]
