# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20160624_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='usrename',
            new_name='username',
        ),
    ]
